/** Default Terms & Conditions — editable per document template in Admin → Setup. */

export const DEFAULT_HOURLY_TERMS = `TERMS & CONDITIONS

Section 1 – General Provisions. (A) For the purposes of this subsection, the following terms will mean: (i) Household goods carrier—The motor carrier/mover contracted to transport a shipment of household goods. (ii) Shipper—The owner of the household goods shipment or his representative. (B) Changes to the moving service contract are not valid unless agreed to in writing by the household goods carrier and the shipper. (C) Household goods carriers will transport shipments with reasonable dispatch. Reasonable dispatch requires the transportation of a shipment within the agreed period of time shown on the moving services contract, except when circumstances beyond the carrier's control, force majeure, prevent or delay transportation. (D) Moving services controls must comply with all other applicable laws of the State of Texas.

Section 2 – Cargo Liability Provisions. (A) The household goods carrier is liable for any loss or damage to the shipment, except as listed in subparagraphs and of this paragraph. (B) The household goods carrier is not responsible for loss, damage, or delay due to acts of God, acts of civil authorities, defects in the shipment, a riot, a strike, or an act or default of the shipper. (C) The household goods carrier is not liable for loss or damage caused by dangerous or explosive goods unless the shipper notifies the carrier, in writing, of the nature of the goods and the carrier agrees, in writing, to the transportation of these goods. (D) The household goods carrier shall not carry or be liable in any way for documents, specie, or for articles of extraordinary value not specifically rated in the published classification or tariffs unless a special agreement to do so and a stipulated value of the articles are endorsed. Items of extraordinary value include but are not limited to: fine art, bank bills, coin or currency, deeds, notes, drafts or valuable papers of any kind, jewelry, postage or revenue stamps, stamp collections, precious stones, articles of particularly inherent value, precious metals or articles manufactured therefrom.

Section 3 – Claims Provisions. (A) A written claim must be filed by the shipper within 90 days of delivery of the shipment to the final destination. In case of failure to make delivery, then a written claim must be filed by the shipper within 90 days after a reasonable time for delivery has elapsed. (B) A household goods carrier is not liable for any claim that is not filed within 90 days of the delivery of the shipment to the final destination. A household goods carrier is not liable for any claim that is not filed within 90 days after a reasonable time for delivery has elapsed for shipments that were not delivered. (C) The process for filing a claim against a household goods carrier and the claims procedures are provided on the website of the Texas Department of Motor Vehicles (department), as well as in the department's administrative rule, 43 Texas Administrative Code §218.61 (relating to Claims). A shipper must file any claims against a household goods carrier within 90 days of the delivery of the shipment to the final destination, or after a reasonable time for delivery has elapsed in the case of failure to make delivery. (D) Claims Processing & Payment Agreement. All claims are subject to the elected valuation coverage and applicable exclusions as detailed within the Valuation Documents, Declaration of Items of Extraordinary Value, General Agreement, and the Terms and Conditions of the Bill of Lading. The Shipper acknowledges and agrees that all claims will be handled in accordance with the Carrier's claims process and/or any third-party claims administrator designated by the Carrier. The Shipper further agrees that they will not: (i) stop payment on any check, (ii) initiate a chargeback, (iii) file a payment dispute, or (iv) take similar action with any financial institution with respect to services rendered and/or any claim, including during the claims process or after a claim determination has been made. Failure to comply with this provision shall constitute a breach of contract and may result in forfeiture of any claim or recovery rights.

Section 4 – Payment Provisions. This shipper must pay the freight charges upon delivery unless the shipper and household goods carrier agree otherwise.

Section 5 – Provisions for Shipments Not Delivered. (A) A household goods carrier may place a shipment of household goods into storage if the shipper is not available for delivery of the goods as scheduled. (B) The cost of such storage is the responsibility of the shipper of the household goods. (C) A shipment of household goods placed in storage is subject to liens for storage, freight, and other lawful charges. (D) A household goods carrier must issue written notice of the storage of the household goods to the shipper at each address shown on the moving services contract within three days of placing the goods in storage. (E) If the shipper refuses to accept or does not claim the household goods within 15 days of the written notice of storage, the household goods carrier may begin the process of selling the goods at public sale, as prescribed in the Transportation Code, Chapter 6. (F) A household goods carrier must give written notice of the public sale to the shipper at each address shown on the moving services contract. (G) The moving services contract does not prohibit the sale of the goods under any other lawful manner if the method set out in the contract cannot be reasonable accomplished.

Section 6 - Replacement Declared Value Protection (A) The Household Goods Carrier is fully insured; it prefers to resolve disputes between itself and its shippers through application of liability, only resorting to insurance when necessary, for the benefit of all parties. (B) The following concerns the carrier's liability: "This Is Not Insurance. A household goods carrier's liability for loss or damage to any shipment is $.60 per pound per article, unless the carrier and shipper agree, in writing, to a greater level of liability." (C) If the carrier and shipper have agreed in writing to a higher limit of liability, the carrier may charge the shipper for this higher limit of liability. If the agreement between the carrier and shipper to a higher limit of liability provides for a deductible, the carrier's liability to pay for loss or damage of property will be reduced by this amount of the deductible. (D) The carrier offers multiple options for a greater level of liability coverage to qualifying shippers at 4 different price points. (i) Bronze Liability Coverage - $99. Provides up to $5,000 worth of liability coverage pending a $100 deductible. (ii) Silver Liability Coverage - $129. Provides up to $10,000 worth of liability coverage pending a $100 deductible. (iii) Gold Liability Coverage - $199. Provides up to $25,000 worth of liability coverage pending a $100 deductible. (iv) Platinum Liability Coverage - $349. Provides up to $50,000 worth of liability coverage pending a $100 deductible. (E) When Replacement Declared Value Protection is ordered in writing by the Shipper, the Carrier will guarantee either (i) the replacement value of articles lost or damaged while in the carrier's custody, (ii) reimbursement cost - as determined by current market value, (iii) or repairs, or the cost of repairs to damaged item(s) to the extent necessary to restore the item to a similar condition as when received by Carrier from the Shipper. (iv) Actual replacement articles, if any, shall consist of articles of like and quality without deduction for appreciation. (F) Exclusions: The same exclusions noted in section 2 apply to Replacement Declared Value Protection.

Section 7 - Concerning the Uninstalling and Installation of Appliances. (A) The Household Goods Carrier does not disconnect or reconnect appliance gas lines or water lines from the wall. (B) The Household Goods Carrier is only equipped to transport household appliances including (but not limited to) refrigerators, washers, dryers, dishwashers, ovens, and grills. (C) It is the Shipper's responsibility to disconnect gas lines and water lines prior to our arrival and reconnect gas lines and water lines during or after our departure. (D) The Shipper waives all Carrier liability and assumes full responsibility for potential water or gas damage.

Section 8 - Maximum Amount to be Charged. TxDMV requires that the Household Goods Carrier state a maximum chargeable amount. The Household Goods Carrier performs its services under non-binding, not-to-exceed proposals with a chargeable ceiling of $25,000 for services rendered.

Section 9 - The provisions expressed in the Moving Services Contract and the Moving Services Contract Addendum precede over the Southwest Movers Association's "Max 4 Tariff" which can be provided upon request.

Section 10 - Additional Claims Exclusions & Acknowledgements (A) Items of Extraordinary Value. Unless items are declared to the Carrier in writing prior to the initial pickup, clearly itemized on the Declaration of Items of Extraordinary Value, and packed/unpacked in the presence of both the Carrier and the Shipper, the Carrier shall not be liable for loss or damage to such items. These items include, but are not limited to: jewelry, watches, precious stones, currency, coins, deeds, securities, legal documents, collectibles, or other items of high inherent value. Such items are considered exceptions to recovery. (B) Particle Board, Engineered, and Assembled Furniture. Particle board, pressboard, ready-to-assemble (RTA), engineered wood, medium-density fiberboard (MDF), reclaimed, repurposed, or recycled wood furniture and similar items are not designed to withstand the normal stresses of moving and are highly susceptible to damage. While the Carrier will make reasonable efforts to transport these items safely, they are considered exceptions to recovery and the Carrier shall not be held liable for damage to such items. (C) Electronics. The Carrier shall not be liable for internal or mechanical damage to electronics, including but not limited to televisions, computers, monitors, or similar devices, unless such damage is the result of external physical damage caused directly by the Carrier and noted at delivery. (D) Acknowledgement. By executing the Moving Services Contract, the Shipper acknowledges that they have read, understand, and agree to all claims procedures, valuation coverage selections, and exclusions outlined herein.`;

export const DEFAULT_FLAT_RATE_TERMS = `TERMS & CONDITIONS — FLAT RATE

Section 1 – General Provisions. (A) For the purposes of this subsection, the following terms will mean: (i) Household goods carrier—The motor carrier/mover contracted to transport a shipment of household goods. (ii) Shipper—The owner of the household goods shipment or his representative. (B) Changes to the moving service contract are not valid unless agreed to in writing by the household goods carrier and the shipper. (C) Household goods carriers will transport shipments with reasonable dispatch. Reasonable dispatch requires the transportation of a shipment within the agreed period of time shown on the moving services contract, except when circumstances beyond the carrier's control, force majeure, prevent or delay transportation. (D) Moving services controls must comply with all other applicable laws of the State of Texas.

Section 2 – Flat Rate Pricing & Scope. (A) The Shipper and Carrier agree to a single, all-inclusive flat rate for the services described in the quote and moving services contract. The flat rate covers labor, truck, standard equipment, blankets, floor protection, and the scope of work agreed upon at the time of booking. (B) The flat rate is binding for the agreed scope. Additional services, access challenges, or changes to the move not reflected in the original scope may require a written change order and adjusted pricing before work proceeds. (C) The flat rate does not include third-party fees, parking permits, tolls, or other pass-through costs unless specifically listed in the quote. (D) Payment of the agreed deposit reserves the move date; the remaining balance is due upon completion unless otherwise agreed in writing.

Section 3 – Cargo Liability Provisions. (A) The household goods carrier is liable for any loss or damage to the shipment, except as listed in this section and Section 10. (B) The household goods carrier is not responsible for loss, damage, or delay due to acts of God, acts of civil authorities, defects in the shipment, a riot, a strike, or an act or default of the shipper. (C) The household goods carrier is not liable for loss or damage caused by dangerous or explosive goods unless the shipper notifies the carrier, in writing, of the nature of the goods and the carrier agrees, in writing, to the transportation of these goods. (D) The household goods carrier shall not carry or be liable in any way for documents, specie, or for articles of extraordinary value not specifically rated unless a special agreement and stipulated value are endorsed in writing.

Section 4 – Claims Provisions. (A) A written claim must be filed by the shipper within 90 days of delivery of the shipment to the final destination. In case of failure to make delivery, then a written claim must be filed by the shipper within 90 days after a reasonable time for delivery has elapsed. (B) A household goods carrier is not liable for any claim that is not filed within 90 days. (C) Claims procedures are provided on the website of the Texas Department of Motor Vehicles and in 43 Texas Administrative Code §218.61. (D) Claims Processing & Payment Agreement. All claims are subject to the elected valuation coverage and applicable exclusions. The Shipper agrees that all claims will be handled in accordance with the Carrier's claims process and/or any third-party claims administrator designated by the Carrier. The Shipper further agrees that they will not stop payment, initiate a chargeback, file a payment dispute, or take similar action with any financial institution with respect to services rendered and/or any claim. Failure to comply may result in forfeiture of claim or recovery rights.

Section 5 – Payment Provisions. The Shipper must pay the agreed flat rate balance upon completion of services unless the Shipper and Carrier agree otherwise in writing. Deposits are non-refundable except as required by law or as stated in the moving services contract.

Section 6 – Provisions for Shipments Not Delivered. (A) A household goods carrier may place a shipment into storage if the shipper is not available for delivery as scheduled. (B) Storage costs are the responsibility of the shipper. (C) Stored shipments are subject to liens for storage, freight, and other lawful charges. (D) Written notice of storage must be issued within three days. (E) If goods are not claimed within 15 days of notice, the carrier may begin the process of public sale as prescribed in the Transportation Code, Chapter 6.

Section 7 - Replacement Declared Value Protection. (A) The Carrier is fully insured and prefers to resolve disputes through application of liability. (B) Base liability is $.60 per pound per article unless the carrier and shipper agree in writing to a greater level. (C) Optional tiers: Bronze ($99 / up to $5,000), Silver ($129 / up to $10,000), Gold ($199 / up to $25,000), Platinum ($349 / up to $50,000), each with a $100 deductible unless otherwise stated. (D) When Replacement Declared Value Protection is ordered in writing, the Carrier will guarantee replacement value, reimbursement at current market value, or repair to restore items to a similar condition. (E) Exclusions in Section 3 apply to Replacement Declared Value Protection.

Section 8 - Concerning the Uninstalling and Installation of Appliances. (A) The Carrier does not disconnect or reconnect appliance gas lines or water lines. (B) The Carrier transports household appliances only. (C) It is the Shipper's responsibility to disconnect and reconnect gas and water lines. (D) The Shipper waives Carrier liability for potential water or gas damage.

Section 9 - Flat Rate Maximum & Tariff. The agreed flat rate stated in the moving services contract is the maximum charge for the described scope. Additional work outside scope requires written authorization. The provisions in the Moving Services Contract and Addendum precede the Southwest Movers Association's "Max 4 Tariff," available upon request.

Section 10 - Additional Claims Exclusions & Acknowledgements. (A) Items of Extraordinary Value must be declared in writing prior to pickup and listed on the Declaration of Items of Extraordinary Value. (B) Particle board, RTA, MDF, and similar furniture are exceptions to recovery. (C) Internal or mechanical damage to electronics is excluded unless caused by external physical damage noted at delivery. (D) By executing the Moving Services Contract, the Shipper acknowledges that they have read, understand, and agree to all terms, valuation selections, and exclusions herein.`;

export const PORTAL_REGULATORY_FOOTER = {
  txDmv: "TX-DMV 006881452C",
  usDot: "US-DOT 2574928",
  copyright: "©2026 JONAH'S MOVERS",
} as const;

/** Split terms text into titled sections for accordion display. */
export function parseTermsSections(text: string): { title: string; body: string }[] {
  const trimmed = text.trim();
  if (!trimmed) return [];

  const parts = trimmed.split(/\n(?=Section \d+)/);
  return parts
    .map((part) => {
      const lines = part.trim().split("\n");
      const first = lines[0]?.trim() ?? "";
      if (first.startsWith("Section ")) {
        const dot = first.indexOf(". ");
        const title = dot > -1 ? first.slice(0, dot) : first;
        const restOfFirst = dot > -1 ? first.slice(dot + 2) : "";
        const body = [restOfFirst, ...lines.slice(1)].filter(Boolean).join("\n").trim();
        return { title, body };
      }
      if (first === "TERMS & CONDITIONS" || first.startsWith("TERMS & CONDITIONS")) {
        return { title: first, body: lines.slice(1).join("\n").trim() };
      }
      return { title: "Terms", body: part.trim() };
    })
    .filter((s) => s.title || s.body);
}
