import type { TeamMemberRecord } from "./types";

export const defaultTeamMembers: TeamMemberRecord[] = [
  {
    id: "tm_1",
    ripplingEmpNo: "0001",
    firstName: "Jonah",
    lastName: "Morrison",
    nickname: "",
    email: "jonah@jonahsmovers.com",
    phone: "(555) 201-1001",
    jobTitles: ["Manager"],
    permissionLevel: "admin",
    hasCrewAppAccess: true,
    hasSoftwareAccess: true,
    payType: "salary",
    payRate: 0,
    salaryAmount: 85000,
    status: "active",
  },
  {
    id: "tm_2",
    ripplingEmpNo: "0002",
    firstName: "Sarah",
    lastName: "Kim",
    nickname: "",
    email: "sarah@jonahsmovers.com",
    phone: "(555) 201-1002",
    jobTitles: ["Manager"],
    permissionLevel: "manager",
    hasCrewAppAccess: false,
    hasSoftwareAccess: true,
    payType: "salary",
    payRate: 0,
    salaryAmount: 55000,
    status: "active",
  },
  {
    id: "tm_3",
    ripplingEmpNo: "2003",
    firstName: "Lisa",
    lastName: "Parker",
    nickname: "",
    email: "lisa@jonahsmovers.com",
    phone: "(555) 201-1003",
    jobTitles: ["Manager"],
    permissionLevel: "operations",
    hasCrewAppAccess: true,
    hasSoftwareAccess: true,
    payType: "hourly",
    payRate: 28,
    salaryAmount: 0,
    status: "active",
  },
  {
    id: "tm_alex",
    ripplingEmpNo: "2001",
    firstName: "Alex",
    lastName: "Rivera",
    nickname: "",
    email: "alex@jonahsmovers.com",
    phone: "(216) 555-0142",
    jobTitles: ["Manager"],
    permissionLevel: "sales",
    hasCrewAppAccess: false,
    hasSoftwareAccess: true,
    payType: "hourly",
    payRate: 22,
    salaryAmount: 0,
    status: "active",
  },
  {
    id: "tm_pat",
    ripplingEmpNo: "2004",
    firstName: "Pat",
    lastName: "Kim",
    nickname: "",
    email: "pat@jonahsmovers.com",
    phone: "(555) 201-1004",
    jobTitles: ["Manager"],
    permissionLevel: "operations",
    capabilityOverrides: { payroll: true },
    hasCrewAppAccess: false,
    hasSoftwareAccess: true,
    payType: "salary",
    payRate: 0,
    salaryAmount: 52000,
    status: "active",
  },
  {
    id: "tm_4",
    ripplingEmpNo: "1005",
    firstName: "Carlos",
    lastName: "Rivera",
    nickname: "Carlos",
    email: "carlos@jonahsmovers.com",
    phone: "(555) 301-1001",
    jobTitles: ["Skipper", "Driver"],
    permissionLevel: "crew",
    hasCrewAppAccess: true,
    hasSoftwareAccess: false,
    payType: "hourly",
    payRate: 32,
    salaryAmount: 0,
    status: "active",
  },
  {
    id: "tm_5",
    ripplingEmpNo: "1003",
    firstName: "Devon",
    lastName: "Lee",
    nickname: "Dev",
    email: "devon@jonahsmovers.com",
    phone: "(555) 301-1002",
    jobTitles: ["Skipper", "Driver"],
    permissionLevel: "crew",
    hasCrewAppAccess: true,
    hasSoftwareAccess: false,
    payType: "hourly",
    payRate: 30,
    salaryAmount: 0,
    status: "active",
  },
  {
    id: "tm_6",
    ripplingEmpNo: "1001",
    firstName: "Marcus",
    lastName: "Thompson",
    nickname: "",
    email: "marcus@jonahsmovers.com",
    phone: "(555) 301-1003",
    jobTitles: ["Mover"],
    permissionLevel: "crew",
    hasCrewAppAccess: true,
    hasSoftwareAccess: false,
    payType: "hourly",
    payRate: 22,
    salaryAmount: 0,
    status: "active",
  },
  {
    id: "tm_7",
    ripplingEmpNo: "1006",
    firstName: "Jordan",
    lastName: "Klein",
    nickname: "",
    email: "jordan@jonahsmovers.com",
    phone: "(555) 301-1005",
    jobTitles: ["Driver", "Mover"],
    permissionLevel: "crew",
    hasCrewAppAccess: true,
    hasSoftwareAccess: false,
    payType: "hourly",
    payRate: 24,
    salaryAmount: 0,
    status: "active",
  },
];
