import type { MessageTemplate } from "./message-templates-types";

export const DEFAULT_MESSAGE_TEMPLATES: MessageTemplate[] = [
  // —— Sales quick replies (manual) ——
  {
    id: "call-voicemail",
    channel: "call",
    label: "Left voicemail",
    category: "sales",
    body: "Left voicemail for {{firstName}} — asked them to call back about their move.",
  },
  {
    id: "call-spoke-interested",
    channel: "call",
    label: "Spoke — interested",
    category: "sales",
    body: "Spoke with {{firstName}}. They're interested in moving forward — answered questions about pricing and next steps.",
  },
  {
    id: "call-callback",
    channel: "call",
    label: "Callback requested",
    category: "sales",
    body: "Spoke with {{firstName}} — requested a callback {{time}}. Will follow up then.",
  },
  {
    id: "call-no-answer",
    channel: "call",
    label: "No answer",
    category: "sales",
    body: "Called {{firstName}} — no answer. Will try again later today.",
  },
  {
    id: "sms-follow-up",
    channel: "sms",
    label: "Quote follow-up",
    category: "sales",
    body: "Hi {{firstName}} — this is {{company}} following up on your estimate. Any questions? Happy to help!",
  },
  {
    id: "sms-booking",
    channel: "sms",
    label: "Ready to book?",
    category: "sales",
    body: "Hi {{firstName}}! Just checking in — still interested in booking your move? Reply here or call us anytime.",
  },
  {
    id: "sms-date-confirm",
    channel: "sms",
    label: "Confirm move date",
    category: "sales",
    body: "Hi {{firstName}}, confirming we're still on for your move on {{moveDate}}. Reply YES to confirm or let us know if anything changed.",
  },
  {
    id: "sms-thanks",
    channel: "sms",
    label: "Thanks for booking",
    category: "sales",
    body: "Thanks {{firstName}}! We've received your booking request. Our team will follow up shortly with next steps.",
  },
  {
    id: "sms-walkthrough-reminder",
    channel: "sms",
    label: "Walkthrough reminder",
    category: "sales",
    body: "Hi {{firstName}} — reminder about your walkthrough with {{rep}}. Reply if you need to reschedule.",
  },
  {
    id: "sms-contract-reminder",
    channel: "sms",
    label: "Contract reminder",
    category: "sales",
    body: "Hi {{firstName}} — your moving agreement is ready to sign. Check your email or reply here if you need help.",
  },
  {
    id: "email-quote-follow-up",
    channel: "email",
    label: "Quote follow-up",
    category: "sales",
    subject: "Your {{company}} estimate",
    body: "Hi {{firstName}},\n\nThank you for considering {{company}} for your upcoming move. I've attached your estimate — please review the scope and let me know if you have any questions.\n\nWhen you're ready, we can hold your date with a deposit.\n\nBest regards,\n{{rep}}",
  },

  // —— Operations (manual) ——
  {
    id: "sms-day-before",
    channel: "sms",
    label: "Day-before reminder",
    category: "ops",
    body: "Hi {{firstName}} — your crew arrives tomorrow! We'll text when we're on the way. Questions? Just reply here.",
  },
  {
    id: "sms-ops-crew-otw",
    channel: "sms",
    label: "Crew on the way",
    category: "ops",
    body: "Hi {{firstName}} — your {{company}} crew is on the way and should arrive shortly. Reply here with any last-minute access notes.",
  },
  {
    id: "sms-ops-claim-received",
    channel: "sms",
    label: "Claim received",
    category: "ops",
    body: "Hi {{firstName}} — we received your damage claim and our ops team is reviewing it. We'll follow up within 1 business day.",
  },
  {
    id: "email-ops-move-confirm",
    channel: "email",
    label: "Move day confirmation",
    category: "ops",
    subject: "Confirmed — your move with {{company}} on {{moveDate}}",
    body: "Hi {{firstName}},\n\nThis confirms your move with {{company}} on {{moveDate}}.\n\nOrigin: {{origin}}\nDestination: {{destination}}\n\nYour crew will contact you on arrival. If anything changes before move day, reply to this email or call {{phone}}.\n\nThank you,\n{{company}} Operations",
  },
  {
    id: "email-ops-claim-received",
    channel: "email",
    label: "Claim acknowledgment",
    category: "ops",
    subject: "We received your claim — {{company}}",
    body: "Hi {{firstName}},\n\nThank you for reporting an issue from your recent move. Our operations team has received your claim and will review the details.\n\nWe'll follow up within one business day with next steps. If you have photos or additional notes, reply to this email.\n\n{{company}} Operations",
  },
  {
    id: "email-ops-damage-followup",
    channel: "email",
    label: "Damage claim follow-up",
    category: "ops",
    subject: "Update on your claim — {{company}}",
    body: "Hi {{firstName}},\n\nFollowing up on your damage claim. We've completed our initial review and would like to discuss resolution options with you.\n\nPlease reply with a good time to call, or reach us at {{phone}}.\n\nThank you,\n{{company}} Operations",
  },
  {
    id: "email-ops-claim-vendor-package",
    channel: "email",
    label: "Claim package to vendor",
    category: "ops",
    subject: "Claim referral — {{moveReference}} · {{fullName}}",
    body: "Hello,\n\nPlease find a new damage claim referral from {{company}}.\n\nCustomer: {{fullName}}\nMove: {{moveReference}}\nMove date: {{moveDate}}\nRoute: {{origin}} → {{destination}}\n\nPhotos and intake notes are in our shared folder. Reply with your availability for a walkthrough or repair estimate.\n\nThank you,\n{{company}} Operations",
  },

  // —— Automated messages (pipeline rules) ——
  {
    id: "sms-quote-sent-confirm",
    channel: "sms",
    label: "Quote sent confirmation",
    category: "automations",
    body: "Hi {{firstName}} — your {{company}} estimate is on the way. Check your email and reply here with any questions!",
  },
  {
    id: "sms-day-before-crew",
    channel: "sms",
    label: "Day before — meet your crew",
    category: "automations",
    body: "Hi {{firstName}} — your {{company}} crew is set for tomorrow! Meet your team & arrival details: {{portalLink}}",
  },
  {
    id: "sms-ops-day-confirm",
    channel: "sms",
    label: "Move day morning confirmation",
    category: "automations",
    body: "Hi {{firstName}} — confirming your move with {{company}} today. Your crew lead will check in on arrival. Questions? Call {{phone}}.",
  },
  {
    id: "sms-review-request",
    channel: "sms",
    label: "Review request",
    category: "automations",
    body: "Hi {{firstName}} — thanks again for choosing {{company}}! How did your crew do? Rate them here: {{feedbackLink}}",
  },
  {
    id: "email-contract-ready",
    channel: "email",
    label: "Contract ready",
    category: "automations",
    subject: "Your moving agreement is ready",
    body: "Hi {{firstName}},\n\nYour moving agreement is ready to sign. Use the link in this email to review valuation options and complete the contract.\n\nReply if anything in the scope needs to change before you sign.\n\nThank you,\n{{rep}}",
  },
  {
    id: "email-booking-confirm",
    channel: "email",
    label: "Booking confirmation",
    category: "automations",
    subject: "You're booked with {{company}}",
    body: "Hi {{firstName}},\n\nYou're booked with {{company}} for {{moveDate}}! We'll confirm crew arrival details as we get closer to move day.\n\nIf your access, inventory, or dates change, let us know as soon as you can.\n\nWe look forward to move day,\n{{rep}}",
  },
  {
    id: "email-day-before-crew",
    channel: "email",
    label: "Day before — meet your crew",
    category: "automations",
    subject: "Tomorrow's crew for your move — {{company}}",
    body: "Hi {{firstName}},\n\nYour move with {{company}} is tomorrow ({{moveDate}}).\n\nMeet your crew, see who's leading the job, and review arrival details here:\n{{portalLink}}\n\nReply to this email or text us at {{phone}} if anything changed.\n\nSee you tomorrow,\n{{company}}",
  },
  {
    id: "email-review-request",
    channel: "email",
    label: "Review request",
    category: "automations",
    subject: "How did we do? — {{company}}",
    body: "Hi {{firstName}},\n\nThank you again for trusting {{company}} with your move. We'd love to hear how your crew did — please take a minute to rate them and leave a comment:\n\n{{feedbackLink}}\n\nYour feedback goes to our operations team first. If everything went great, we'll also share a link where you can leave a public Google review.\n\nWith gratitude,\n{{company}}",
  },
];

export function defaultMessageTemplates(): MessageTemplate[] {
  return DEFAULT_MESSAGE_TEMPLATES.map((t) => ({ ...t }));
}
