import { MOCK_MOVES } from "@/lib/moves/mock-data";
import { isMoveLost } from "@/lib/moves/move-pipeline";
import type { MoveRecord } from "@/lib/moves/types";
import type { OrganizationRecord, PersonKind, PersonRecord, VendorType } from "./types";

function vendorOrg(opts: {
  id: string;
  name: string;
  phone: string;
  email: string;
  address: string;
  website: string | null;
  notes: string;
}): OrganizationRecord {
  return {
    id: opts.id,
    name: opts.name,
    orgType: "vendor",
    phone: opts.phone,
    email: opts.email,
    address: opts.address,
    website: opts.website,
    primaryContactId: `${opts.id}-contact`,
    moveIds: [],
    notes: opts.notes,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  };
}

function vendorContact(opts: {
  orgId: string;
  name: string;
  vendorType: VendorType;
  phone: string;
  email: string;
  title: string;
}): PersonRecord {
  return {
    id: `${opts.orgId}-contact`,
    name: opts.name,
    kind: "vendor",
    referralType: null,
    vendorType: opts.vendorType,
    phone: opts.phone,
    email: opts.email,
    organizationId: opts.orgId,
    title: opts.title,
    moveIds: [],
    notes: null,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  };
}

/** New vendor organizations grouped so every vendor type has 3–4 entries. */
const VENDOR_TEST_ORGS: OrganizationRecord[] = [
  // truck_fleet
  vendorOrg({
    id: "org-penske-trucks",
    name: "Penske Truck Rental",
    phone: "(216) 555-9001",
    email: "fleet@penske.example",
    address: "4500 Tiedeman Rd, Brooklyn, OH",
    website: "penske.example",
    notes: "Box trucks and tractors — overflow fleet rental.",
  }),
  vendorOrg({
    id: "org-ryder-fleet",
    name: "Ryder Commercial Fleet",
    phone: "(216) 555-9002",
    email: "leasing@ryderfleet.example",
    address: "7000 Grant Ave, Cleveland, OH",
    website: "ryderfleet.example",
    notes: "Long-term truck leasing and seasonal capacity.",
  }),
  // operations_materials
  vendorOrg({
    id: "org-uline-supply",
    name: "Uline Packing Supply",
    phone: "(800) 555-9100",
    email: "orders@ulinesupply.example",
    address: "Pleasant Prairie, WI",
    website: "ulinesupply.example",
    notes: "Boxes, tape, and mailers — next-day bulk delivery.",
  }),
  vendorOrg({
    id: "org-cratewerks-cartons",
    name: "CrateWerks Carton Co.",
    phone: "(216) 555-9101",
    email: "sales@cratewerks.example",
    address: "1450 W 117th St, Cleveland, OH",
    website: "cratewerks.example",
    notes: "Wardrobe cartons, dish packs, and custom inserts.",
  }),
  // claim_repairs
  vendorOrg({
    id: "org-restorepro-furniture",
    name: "RestorePro Furniture Repair",
    phone: "(440) 555-9200",
    email: "claims@restorepro.example",
    address: "330 E Bagley Rd, Berea, OH",
    website: "restorepro.example",
    notes: "Furniture refinishing and transit-damage claims.",
  }),
  // crew_vendors
  vendorOrg({
    id: "org-laborlink-crews",
    name: "LaborLink Day Crews",
    phone: "(216) 555-9300",
    email: "staffing@laborlink.example",
    address: "2900 Detroit Ave, Cleveland, OH",
    website: "laborlink.example",
    notes: "On-demand load/unload labor for peak days.",
  }),
  // hr_vendors
  vendorOrg({
    id: "org-benefitfirst",
    name: "BenefitFirst Group",
    phone: "(216) 555-9400",
    email: "advisors@benefitfirst.example",
    address: "1375 E 9th St, Cleveland, OH",
    website: "benefitfirst.example",
    notes: "Health, dental, and 401(k) benefits brokerage.",
  }),
  vendorOrg({
    id: "org-corp-chaplains",
    name: "Corporate Chaplains of Ohio",
    phone: "(440) 555-9401",
    email: "care@corpchaplains.example",
    address: "Strongsville, OH",
    website: "corpchaplains.example",
    notes: "Employee care and chaplaincy program.",
  }),
  vendorOrg({
    id: "org-safework-screening",
    name: "SafeWork Screening",
    phone: "(216) 555-9402",
    email: "intake@safeworkscreen.example",
    address: "6200 Rockside Woods Blvd, Independence, OH",
    website: "safeworkscreen.example",
    notes: "Background checks and DOT drug screening.",
  }),
  // fleet_repair
  vendorOrg({
    id: "org-diesel-doctors",
    name: "Diesel Doctors Truck Repair",
    phone: "(216) 555-9500",
    email: "shop@dieseldoctors.example",
    address: "3801 Train Ave, Cleveland, OH",
    website: "dieseldoctors.example",
    notes: "Engine, brake, and DOT inspection service.",
  }),
  vendorOrg({
    id: "org-liftgate-techs",
    name: "LiftGate Techs",
    phone: "(440) 555-9501",
    email: "service@liftgatetechs.example",
    address: "120 Alpha Park, Highland Heights, OH",
    website: "liftgatetechs.example",
    notes: "Lift gate repair and hydraulic service.",
  }),
  vendorOrg({
    id: "org-fleetcare-tire",
    name: "FleetCare Tire & Brake",
    phone: "(216) 555-9502",
    email: "service@fleetcaretire.example",
    address: "5500 Brookpark Rd, Parma, OH",
    website: "fleetcaretire.example",
    notes: "Commercial tires, alignment, and brake work.",
  }),
];

/**
 * Vendor contacts — one per vendor org so each org is categorized by vendor
 * type (existing vendor orgs included so they stop matching every type filter).
 */
const VENDOR_TEST_CONTACTS: PersonRecord[] = [
  // Existing vendor orgs (org-shamrock-crating already has a vendor contact)
  vendorContact({
    orgId: "org-allegro-piano",
    name: "Tony Marsh",
    vendorType: "special_services",
    phone: "(216) 555-8121",
    email: "tony@allegropiano.example",
    title: "Scheduling lead",
  }),
  vendorContact({
    orgId: "org-summit-hoisting",
    name: "Rick Vance",
    vendorType: "special_services",
    phone: "(216) 555-4408",
    email: "rick@summithoisting.example",
    title: "Rigging supervisor",
  }),
  vendorContact({
    orgId: "org-proshine-cleaning",
    name: "Dana Pruitt",
    vendorType: "crew_vendors",
    phone: "(440) 555-9913",
    email: "dana@proshineclean.example",
    title: "Crew lead",
  }),
  vendorContact({
    orgId: "org-haulaway-junk",
    name: "Marcus Lee",
    vendorType: "crew_vendors",
    phone: "(216) 555-6656",
    email: "marcus@haulawayjunk.example",
    title: "Dispatch",
  }),
  vendorContact({
    orgId: "org-greatlakes-appliance",
    name: "Priya Nair",
    vendorType: "claim_repairs",
    phone: "(440) 555-3381",
    email: "priya@glappliance.example",
    title: "Service manager",
  }),
  vendorContact({
    orgId: "org-buckeye-supplies",
    name: "Sam Okafor",
    vendorType: "operations_materials",
    phone: "(216) 555-2281",
    email: "sam@buckeyesupplies.example",
    title: "Account rep",
  }),
  vendorContact({
    orgId: "org-whiteglove-auto",
    name: "Gloria Reyes",
    vendorType: "truck_fleet",
    phone: "(800) 555-7042",
    email: "gloria@whitegloveauto.example",
    title: "Logistics coordinator",
  }),
  vendorContact({
    orgId: "org-maple-handyman",
    name: "Owen Pratt",
    vendorType: "claim_repairs",
    phone: "(216) 555-5191",
    email: "owen@maplehandyman.example",
    title: "Owner",
  }),
  // New vendor orgs
  vendorContact({
    orgId: "org-penske-trucks",
    name: "Beth Carlson",
    vendorType: "truck_fleet",
    phone: "(216) 555-9003",
    email: "beth@penske.example",
    title: "Fleet account rep",
  }),
  vendorContact({
    orgId: "org-ryder-fleet",
    name: "Hal Dwyer",
    vendorType: "truck_fleet",
    phone: "(216) 555-9004",
    email: "hal@ryderfleet.example",
    title: "Leasing manager",
  }),
  vendorContact({
    orgId: "org-uline-supply",
    name: "Megan Ross",
    vendorType: "operations_materials",
    phone: "(800) 555-9102",
    email: "megan@ulinesupply.example",
    title: "Account rep",
  }),
  vendorContact({
    orgId: "org-cratewerks-cartons",
    name: "Victor Hsu",
    vendorType: "operations_materials",
    phone: "(216) 555-9103",
    email: "victor@cratewerks.example",
    title: "Sales",
  }),
  vendorContact({
    orgId: "org-restorepro-furniture",
    name: "Nadia Khan",
    vendorType: "claim_repairs",
    phone: "(440) 555-9201",
    email: "nadia@restorepro.example",
    title: "Repair tech lead",
  }),
  vendorContact({
    orgId: "org-laborlink-crews",
    name: "Trent Boyd",
    vendorType: "crew_vendors",
    phone: "(216) 555-9301",
    email: "trent@laborlink.example",
    title: "Staffing coordinator",
  }),
  vendorContact({
    orgId: "org-benefitfirst",
    name: "Carla Mendez",
    vendorType: "hr_vendors",
    phone: "(216) 555-9403",
    email: "carla@benefitfirst.example",
    title: "Benefits advisor",
  }),
  vendorContact({
    orgId: "org-corp-chaplains",
    name: "Dale Means",
    vendorType: "hr_vendors",
    phone: "(440) 555-9404",
    email: "dale@corpchaplains.example",
    title: "Chaplain",
  }),
  vendorContact({
    orgId: "org-safework-screening",
    name: "Janet Cole",
    vendorType: "hr_vendors",
    phone: "(216) 555-9405",
    email: "janet@safeworkscreen.example",
    title: "Account manager",
  }),
  vendorContact({
    orgId: "org-diesel-doctors",
    name: "Manny Ortiz",
    vendorType: "fleet_repair",
    phone: "(216) 555-9503",
    email: "manny@dieseldoctors.example",
    title: "Shop foreman",
  }),
  vendorContact({
    orgId: "org-liftgate-techs",
    name: "Kurt Hahn",
    vendorType: "fleet_repair",
    phone: "(440) 555-9504",
    email: "kurt@liftgatetechs.example",
    title: "Service tech",
  }),
  vendorContact({
    orgId: "org-fleetcare-tire",
    name: "Lena Park",
    vendorType: "fleet_repair",
    phone: "(216) 555-9505",
    email: "lena@fleetcaretire.example",
    title: "Service writer",
  }),
];

export const MOCK_ORGANIZATIONS: OrganizationRecord[] = [
  {
    id: "org-whitfield-realty",
    name: "Whitfield Realty",
    orgType: "realtor",
    phone: "(216) 555-8800",
    email: "info@whitfieldrealty.example",
    address: "1200 Euclid Ave, Cleveland, OH",
    website: "whitfieldrealty.example",
    primaryContactId: "person-karen-whitfield",
    moveIds: ["mv-quote-sent"],
    notes: "Strong referral partner — send thank-you after close",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "org-northside-dental",
    name: "Northside Dental Group",
    orgType: "commercial",
    phone: "(216) 555-0330",
    email: "office@northsidedental.example",
    address: "6000 Rockside Rd, Independence, OH",
    website: null,
    primaryContactId: "person-northside-office",
    moveIds: ["mv-waiting-info"],
    notes: "Commercial relocation — equipment list pending",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "org-sunset-senior",
    name: "Sunset Ridge Senior Living",
    orgType: "senior_living",
    phone: "(440) 555-2100",
    email: "transitions@sunsetridge.example",
    address: "4400 Mentor Ave, Mentor, OH",
    website: "sunsetridge.example",
    primaryContactId: "person-sunset-coordinator",
    moveIds: ["mv-needs-contract"],
    notes: "Preferred vendor for resident moves — COI on file",
    createdAt: "2023-06-15T00:00:00Z",
    updatedAt: "2026-05-19T00:00:00Z",
  },
  {
    id: "org-cleveland-storage",
    name: "Cleveland Climate Storage",
    orgType: "storage_facility",
    phone: "(216) 555-7700",
    email: "dispatch@clevelandstorage.example",
    address: "1800 Carnegie Ave, Cleveland, OH",
    website: null,
    primaryContactId: "person-storage-dispatch",
    moveIds: ["mv-booked"],
    notes: "Warehouse partner for multi-day / storage legs",
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2026-05-10T00:00:00Z",
  },
  {
    id: "org-shamrock-crating",
    name: "Shamrock Crating & Fine Art",
    orgType: "vendor",
    phone: "(216) 555-3310",
    email: "dispatch@shamrockcrating.example",
    address: "2200 Superior Ave, Cleveland, OH",
    website: "shamrockcrating.example",
    primaryContactId: "person-shamrock-dispatch",
    moveIds: ["mv-needs-contract"],
    notes: "Preferred crating vendor — piano, art, marble",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
  },
  {
    id: "org-peterson-estate",
    name: "Peterson Estate (law office)",
    orgType: "other",
    phone: "(440) 555-0190",
    email: "estates@petersonlaw.example",
    address: "88 Euclid Ave, Cleveland, OH",
    website: null,
    primaryContactId: "person-peterson-executor",
    moveIds: ["mv-waiting-walkthrough"],
    notes: "Estate move — executor is primary contact",
    createdAt: "2026-05-10T00:00:00Z",
    updatedAt: "2026-05-19T00:00:00Z",
  },
  {
    id: "org-a-better-tripp",
    name: "A Better Tripp",
    orgType: "moving_company",
    phone: "(216) 555-2040",
    email: "referrals@abettertripp.example",
    address: "Cleveland, OH",
    website: "abettertripp.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Moving-company referral partner — 10% commission on referred jobs",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-15T00:00:00Z",
  },
  {
    id: "org-frontier-moving",
    name: "Frontier",
    orgType: "moving_company",
    phone: "(440) 555-7720",
    email: "dispatch@frontiermoving.example",
    address: "Akron, OH",
    website: "frontiermoving.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Moving-company referral partner — 10% commission on referred jobs",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-15T00:00:00Z",
  },
  {
    id: "org-allegro-piano",
    name: "Allegro Piano Movers",
    orgType: "vendor",
    phone: "(216) 555-8120",
    email: "schedule@allegropiano.example",
    address: "910 Train Ave, Cleveland, OH",
    website: "allegropiano.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Grand pianos, organs, and safes — specialty handling.",
    createdAt: "2025-04-12T00:00:00Z",
    updatedAt: "2026-05-22T00:00:00Z",
  },
  {
    id: "org-summit-hoisting",
    name: "Summit Hoisting & Rigging",
    orgType: "vendor",
    phone: "(216) 555-4407",
    email: "ops@summithoisting.example",
    address: "3300 W 65th St, Cleveland, OH",
    website: "summithoisting.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Crane and window hoists for high-rise / oversized items.",
    createdAt: "2025-01-20T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
  },
  {
    id: "org-proshine-cleaning",
    name: "ProShine Move-Out Cleaning",
    orgType: "vendor",
    phone: "(440) 555-9912",
    email: "bookings@proshineclean.example",
    address: "120 Front St, Berea, OH",
    website: "proshineclean.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Final cleans and carpet shampoo for move-outs.",
    createdAt: "2025-07-08T00:00:00Z",
    updatedAt: "2026-05-30T00:00:00Z",
  },
  {
    id: "org-haulaway-junk",
    name: "HaulAway Junk Removal",
    orgType: "vendor",
    phone: "(216) 555-6655",
    email: "dispatch@haulawayjunk.example",
    address: "5400 Broadway Ave, Cleveland, OH",
    website: "haulawayjunk.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Debris, donations, and disposal on move day.",
    createdAt: "2025-03-18T00:00:00Z",
    updatedAt: "2026-06-02T00:00:00Z",
  },
  {
    id: "org-greatlakes-appliance",
    name: "Great Lakes Appliance Service",
    orgType: "vendor",
    phone: "(440) 555-3380",
    email: "service@glappliance.example",
    address: "780 Lloyd Rd, Wickliffe, OH",
    website: "glappliance.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Disconnect / reconnect washers, gas ranges, and ice lines.",
    createdAt: "2025-05-02T00:00:00Z",
    updatedAt: "2026-05-28T00:00:00Z",
  },
  {
    id: "org-buckeye-supplies",
    name: "Buckeye Packing Supplies",
    orgType: "vendor",
    phone: "(216) 555-2280",
    email: "orders@buckeyesupplies.example",
    address: "2100 Hamilton Ave, Cleveland, OH",
    website: "buckeyesupplies.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Boxes, wardrobe cartons, and packing materials — bulk pricing.",
    createdAt: "2024-11-05T00:00:00Z",
    updatedAt: "2026-05-12T00:00:00Z",
  },
  {
    id: "org-whiteglove-auto",
    name: "WhiteGlove Auto Transport",
    orgType: "vendor",
    phone: "(800) 555-7041",
    email: "quotes@whitegloveauto.example",
    address: "Independence, OH",
    website: "whitegloveauto.example",
    primaryContactId: null,
    moveIds: [],
    notes: "Enclosed vehicle transport for long-distance moves.",
    createdAt: "2025-08-14T00:00:00Z",
    updatedAt: "2026-06-04T00:00:00Z",
  },
  {
    id: "org-maple-handyman",
    name: "Maple Handyman & Repair",
    orgType: "vendor",
    phone: "(216) 555-5190",
    email: "jobs@maplehandyman.example",
    address: "640 Larchmere Blvd, Cleveland, OH",
    website: null,
    primaryContactId: null,
    moveIds: [],
    notes: "Mounting, assembly, and minor repairs at delivery.",
    createdAt: "2025-09-22T00:00:00Z",
    updatedAt: "2026-06-08T00:00:00Z",
  },
  ...VENDOR_TEST_ORGS,
];

function kindFromMove(move: MoveRecord): PersonKind {
  if (move.pipelineStage === "completed") return "customer";
  if (move.pipelineStage === "booked") return "customer";
  if (isMoveLost(move)) return "lead";
  return "lead";
}

function customerPersonFromMove(move: MoveRecord): PersonRecord {
  return {
    id: `person-${move.id}-customer`,
    name: move.customerName,
    kind: kindFromMove(move),
    referralType: null,
    vendorType: null,
    phone: move.customerPhone,
    email: move.customerEmail,
    organizationId: null,
    title: null,
    moveIds: [move.id],
    notes: null,
    createdAt: move.createdAt,
    updatedAt: move.updatedAt,
  };
}

const STANDALONE_PEOPLE: PersonRecord[] = [
  {
    id: "person-karen-whitfield",
    name: "Karen Whitfield",
    kind: "referral",
    referralType: "realtor",
    vendorType: null,
    phone: "(216) 555-8801",
    email: "karen@whitfieldrealty.example",
    organizationId: "org-whitfield-realty",
    title: "Listing agent",
    moveIds: ["mv-quote-sent"],
    notes: "Referred Walsh family — repeat sender",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "person-northside-office",
    name: "Office Manager — Northside",
    kind: "lead",
    referralType: null,
    vendorType: null,
    phone: "(216) 555-0330",
    email: "office@northsidedental.example",
    organizationId: "org-northside-dental",
    title: "Office manager",
    moveIds: ["mv-waiting-info"],
    notes: null,
    createdAt: "2026-05-17T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "person-sunset-coordinator",
    name: "Maria Santos",
    kind: "referral",
    referralType: "senior_living",
    vendorType: null,
    phone: "(440) 555-2102",
    email: "msantos@sunsetridge.example",
    organizationId: "org-sunset-senior",
    title: "Transition coordinator",
    moveIds: ["mv-needs-contract"],
    notes: "Referred Ellis long-distance move",
    createdAt: "2026-04-20T00:00:00Z",
    updatedAt: "2026-05-19T00:00:00Z",
  },
  {
    id: "person-shamrock-dispatch",
    name: "Alex Rivera",
    kind: "vendor",
    referralType: null,
    vendorType: "special_services",
    phone: "(216) 555-3311",
    email: "alex@shamrockcrating.example",
    organizationId: "org-shamrock-crating",
    title: "Dispatch",
    moveIds: ["mv-needs-contract"],
    notes: "Crating quotes — 48 hr lead time",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
  },
  {
    id: "person-storage-dispatch",
    name: "Dispatch — Cleveland Storage",
    kind: "vendor",
    referralType: null,
    vendorType: "operations_materials",
    phone: "(216) 555-7701",
    email: "dispatch@clevelandstorage.example",
    organizationId: "org-cleveland-storage",
    title: "Dispatch",
    moveIds: ["mv-booked"],
    notes: null,
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
  },
  {
    id: "person-peterson-executor",
    name: "James Peterson (executor)",
    kind: "lead",
    referralType: null,
    vendorType: null,
    phone: "(440) 555-0198",
    email: "jpeterson.law@example.com",
    organizationId: "org-peterson-estate",
    title: "Executor",
    moveIds: ["mv-waiting-walkthrough"],
    notes: "On-site walkthrough scheduled",
    createdAt: "2026-05-10T00:00:00Z",
    updatedAt: "2026-05-19T00:00:00Z",
  },
  {
    id: "person-angela-spouse",
    name: "David Brooks",
    kind: "other",
    referralType: null,
    vendorType: null,
    phone: "(216) 555-0824",
    email: "dbrooks@example.com",
    organizationId: null,
    title: "Care of — spouse",
    moveIds: ["mv-complete"],
    notes: "Secondary contact on completed move",
    createdAt: "2026-04-20T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "person-mike-restoration",
    name: "Mike Torres",
    kind: "referral",
    referralType: "restoration_company",
    vendorType: null,
    phone: "(216) 555-4420",
    email: "mtorres@rapidrestore.example",
    organizationId: null,
    title: "Project manager — Rapid Restore",
    moveIds: [],
    notes: "Water damage referrals — prefers same-week estimates",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
  },
  {
    id: "person-lisa-developer",
    name: "Lisa Chen",
    kind: "referral",
    referralType: "developer",
    vendorType: null,
    phone: "(440) 555-3300",
    email: "lchen@lakewoodheightsdev.example",
    organizationId: null,
    title: "Community sales — Lakewood Heights",
    moveIds: [],
    notes: "New build move-ins — bulk pricing discussions",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
  },
  ...VENDOR_TEST_CONTACTS,
];

export const MOCK_PEOPLE: PersonRecord[] = [
  ...MOCK_MOVES.map(customerPersonFromMove),
  ...STANDALONE_PEOPLE,
];

export function getPersonById(id: string): PersonRecord | undefined {
  return MOCK_PEOPLE.find((p) => p.id === id);
}

export function getOrganizationById(id: string): OrganizationRecord | undefined {
  return MOCK_ORGANIZATIONS.find((o) => o.id === id);
}

export function getOrganizationForPerson(person: PersonRecord): OrganizationRecord | undefined {
  if (!person.organizationId) return undefined;
  return getOrganizationById(person.organizationId);
}

export function getPeopleForOrganization(orgId: string): PersonRecord[] {
  return MOCK_PEOPLE.filter((p) => p.organizationId === orgId);
}

export function directoryCounts() {
  return {
    people: MOCK_PEOPLE.length,
    organizations: MOCK_ORGANIZATIONS.length,
    customers: MOCK_PEOPLE.filter((p) => p.kind === "customer").length,
    leads: MOCK_PEOPLE.filter((p) => p.kind === "lead").length,
    referrals: MOCK_PEOPLE.filter((p) => p.kind === "referral").length,
  };
}
