import { addDays, toDateKey } from "@/lib/calendar/date-utils";
import { REAL_ADMIN_PERSONA } from "@/lib/session/personas";
import { buildRecurrenceLabel, weekdayFromDateKey } from "./recurrence";
import type { StaffCalendarEvent } from "./types";

function at(dayOffset: number, startHour: number, startMin: number, endHour: number, endMin: number) {
  const date = addDays(new Date(), dayOffset);
  return {
    dateKey: toDateKey(date),
    startMinutes: startHour * 60 + startMin,
    endMinutes: endHour * 60 + endMin,
  };
}

/** Demo staff calendar — replace with Outlook Graph sync when integration is live. */
export function buildStaffCalendarEvents(
  staffId: string = REAL_ADMIN_PERSONA.id,
  staffName: string = REAL_ADMIN_PERSONA.name,
): StaffCalendarEvent[] {
  const e = (
    id: string,
    title: string,
    dayOffset: number,
    startH: number,
    startM: number,
    endH: number,
    endM: number,
    staffId: string,
    staffName: string,
    department: StaffCalendarEvent["department"],
    extra?: Partial<StaffCalendarEvent>,
  ): StaffCalendarEvent => {
    const slot = at(dayOffset, startH, startM, endH, endM);
    return {
      id,
      title,
      ...slot,
      staffId,
      staffName,
      department,
      outlookSynced: true,
      source: "outlook" as const,
      ...extra,
    };
  };

  return [
    e(
      "ev-alex-2",
      "Quote follow-up block",
      1,
      14,
      0,
      15,
      0,
      staffId,
      staffName,
      "sales",
    ),
    e(
      "ev-alex-3",
      "Sales standup",
      2,
      8,
      30,
      9,
      0,
      staffId,
      staffName,
      "sales",
      {
        location: "Teams",
        kind: "standup",
        recurrence: (() => {
          const standupDateKey = at(2, 8, 30, 9, 0).dateKey;
          const pattern = {
            type: "weekly" as const,
            interval: 1,
            daysOfWeek: [weekdayFromDateKey(standupDateKey)],
          };
          return {
            label: buildRecurrenceLabel(pattern, standupDateKey),
            pattern,
            range: { type: "noEnd" as const },
            startDate: standupDateKey,
          };
        })(),
        notes: "Quick pipeline + dispatch check-in.",
      },
    ),
    e(
      "ev-alex-4",
      "Virtual estimate — Chen family",
      3,
      11,
      0,
      11,
      45,
      staffId,
      staffName,
      "sales",
      { kind: "estimate_virtual", location: "Teams" },
    ),
    e(
      "ev-sarah-1",
      "Realtor lunch — Keller Williams",
      0,
      12,
      0,
      13,
      0,
      "tm_2",
      "Sarah Kim",
      "sales",
      { kind: "meeting" },
    ),
    e(
      "ev-sarah-2",
      "Pipeline review",
      2,
      15,
      0,
      16,
      0,
      "tm_2",
      "Sarah Kim",
      "sales",
      { location: "Office", kind: "meeting" },
    ),
    e(
      "ev-lisa-1",
      "Dispatch huddle",
      0,
      7,
      30,
      8,
      0,
      "tm_3",
      "Lisa Parker",
      "operations",
      { kind: "standup" },
    ),
    e(
      "ev-lisa-2",
      "Fleet vendor call",
      1,
      13,
      30,
      14,
      30,
      "tm_3",
      "Lisa Parker",
      "operations",
      { kind: "call" },
    ),
    e(
      "ev-lisa-3",
      "Ops prep — weekend board",
      3,
      9,
      0,
      10,
      0,
      "tm_3",
      "Lisa Parker",
      "operations",
      { location: "Office" },
    ),
    e(
      "ev-lisa-4",
      "Crew time-off reviews",
      5,
      8,
      0,
      9,
      0,
      "tm_3",
      "Lisa Parker",
      "operations",
    ),
    e(
      "ev-jonah-1",
      "Owner check-in",
      2,
      11,
      0,
      12,
      0,
      "tm_1",
      "Jonah Morrison",
      "operations",
    ),
    e(
      "ev-jonah-2",
      "Insurance renewal call",
      4,
      14,
      0,
      15,
      0,
      "tm_1",
      "Jonah Morrison",
      "operations",
      { kind: "call" },
    ),
    e(
      "ev-company-1",
      "All-hands — Q3 goals",
      5,
      12,
      0,
      13,
      0,
      "tm_1",
      "Jonah Morrison",
      "operations",
      { location: "Main office", kind: "meeting" },
    ),
    e(
      "ev-company-2",
      "All-hands — Q3 goals",
      5,
      12,
      0,
      13,
      0,
      "tm_2",
      "Sarah Kim",
      "sales",
      { location: "Main office", kind: "meeting" },
    ),
    e(
      "ev-company-3",
      "All-hands — Q3 goals",
      5,
      12,
      0,
      13,
      0,
      "tm_3",
      "Lisa Parker",
      "operations",
      { location: "Main office", kind: "meeting" },
    ),
    e(
      "ev-company-4",
      "All-hands — Q3 goals",
      5,
      12,
      0,
      13,
      0,
      staffId,
      staffName,
      "sales",
      { location: "Main office", kind: "meeting" },
    ),
  ];
}
