import { buildRipplingPayrollRows, ripplingPayrollCsvContent } from "./rippling-export";
import type { PayPeriod, TimeEntry } from "./types";

export { buildRipplingPayrollRows, ripplingPayrollCsvContent } from "./rippling-export";

export const PAY_PERIODS: PayPeriod[] = [
  { id: "pp-current", label: "Current week (May 19–25)", start: "2026-05-19", end: "2026-05-25" },
  { id: "pp-prev", label: "Previous week (May 12–18)", start: "2026-05-12", end: "2026-05-18" },
];

export const MOCK_TIME_ENTRIES: TimeEntry[] = [
  {
    id: "te-1",
    personName: "Marcus T.",
    workerType: "crew",
    roleLabel: "Skipper",
    date: "2026-05-20",
    jobRef: "MV-BOOKED",
    clockIn: "07:02",
    clockOut: "15:48",
    breakMinutes: 30,
    hours: 8.27,
    hourlyRate: 22,
    status: "approved",
    source: "crew_app",
  },
  {
    id: "te-2",
    personName: "Tyler Brooks",
    workerType: "crew",
    roleLabel: "Skipper / Driver",
    date: "2026-05-20",
    jobRef: "MV-BOOKED",
    clockIn: "07:05",
    clockOut: "16:10",
    breakMinutes: 30,
    hours: 8.58,
    hourlyRate: 21,
    status: "approved",
    source: "crew_app",
  },
  {
    id: "te-3",
    personName: "Devon Lee",
    workerType: "crew",
    roleLabel: "Driver",
    date: "2026-05-20",
    jobRef: "MV-BOOKED",
    clockIn: "07:10",
    clockOut: "14:55",
    breakMinutes: 30,
    hours: 7.25,
    hourlyRate: 19,
    status: "pending",
    source: "crew_app",
    notes: "Clock-out looks early — verify with dispatch",
  },
  {
    id: "te-4",
    personName: "Alex Rivera",
    workerType: "office",
    roleLabel: "Sales · hourly",
    date: "2026-05-20",
    jobRef: null,
    clockIn: "08:30",
    clockOut: "17:15",
    breakMinutes: 60,
    hours: 7.75,
    hourlyRate: 24,
    status: "approved",
    source: "office_manual",
  },
  {
    id: "te-5",
    personName: "Jordan Lee",
    workerType: "office",
    roleLabel: "Sales · hourly",
    date: "2026-05-19",
    jobRef: null,
    clockIn: "09:00",
    clockOut: "18:00",
    breakMinutes: 60,
    hours: 8,
    hourlyRate: 23,
    status: "approved",
    source: "office_manual",
  },
  {
    id: "te-6",
    personName: "Lisa Parker",
    workerType: "office",
    roleLabel: "Operations · hourly",
    date: "2026-05-20",
    jobRef: null,
    clockIn: "07:00",
    clockOut: "16:30",
    breakMinutes: 45,
    hours: 8.25,
    hourlyRate: 28,
    status: "pending",
    source: "manager_edit",
    notes: "Adjusted lunch break per timesheet",
  },
  {
    id: "te-7",
    personName: "Sam R.",
    workerType: "crew",
    roleLabel: "Mover",
    date: "2026-05-19",
    jobRef: "MV-AI",
    clockIn: "06:55",
    clockOut: "15:20",
    breakMinutes: 30,
    hours: 7.92,
    hourlyRate: 18,
    status: "approved",
    source: "crew_app",
  },
  {
    id: "te-8",
    personName: "Mia Chen",
    workerType: "office",
    roleLabel: "Coordinator · salary",
    date: "2026-05-20",
    jobRef: null,
    clockIn: "08:00",
    clockOut: "17:00",
    breakMinutes: 60,
    hours: 8,
    hourlyRate: null,
    status: "approved",
    source: "office_manual",
    notes: "Salaried — hours tracked for job costing only",
  },
];

export function entriesInPeriod(entries: TimeEntry[], period: PayPeriod): TimeEntry[] {
  return entries.filter((e) => e.date >= period.start && e.date <= period.end);
}

