import type { ClaimsStore, MoveClaim } from "./claims-types";

const now = "2026-05-19T10:00:00Z";

export const DEFAULT_CLAIMS: MoveClaim[] = [
  {
    id: "clm-1",
    reference: "CLM-1041",
    moveId: "mv-booked",
    customerName: "Patricia & James Okonkwo",
    moveReference: "MV-BOOKED",
    jobDayId: "mv-booked-jd2",
    jobDayLabel: "Day 2",
    status: "new",
    category: "damage",
    title: "Scratched hardwood — dining room",
    description: "Customer reported gouges after furniture placement. Photos in move file.",
    reportedDate: "2026-05-20",
    amountClaimed: 2400,
    amountReserved: 0,
    amountPaid: 0,
    assignedTo: "Alex Rivera",
    reportedBy: "Skipper — Marcus T.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "clm-2",
    reference: "CLM-1038",
    moveId: "mv-complete-2day",
    customerName: "Helen & Robert Marsh",
    moveReference: "MV-COMPLETE-2D",
    jobDayId: "mv-complete-2day-jd2",
    jobDayLabel: "Day 2",
    status: "in_progress",
    category: "damage",
    title: "Wall scuff — stair landing",
    description: "Touch-up paint and patch quoted; vendor walkthrough scheduled.",
    reportedDate: "2026-05-12",
    amountClaimed: 850,
    amountReserved: 600,
    amountPaid: 0,
    assignedTo: "Mia Chen",
    reportedBy: "Customer call",
    notes: "Got two repair bids — using lower bid pending customer OK.",
    createdAt: "2026-05-12T14:00:00Z",
    updatedAt: now,
  },
  {
    id: "clm-3",
    reference: "CLM-1035",
    moveId: "mv-complete",
    customerName: "Denise Carter",
    moveReference: "MV-COMPLETE",
    status: "pending",
    category: "billing",
    title: "Disputed overtime charge",
    description: "Customer disputes 1.5 hrs over quote; reviewing time sheet and GPS.",
    reportedDate: "2026-05-08",
    pendingReason: "internal",
    amountClaimed: 420,
    amountReserved: 0,
    amountPaid: 0,
    assignedTo: "Jordan Lee",
    reportedBy: "Billing",
    notes: "Waiting on ops lead to sign off on adjustment.",
    createdAt: "2026-05-08T09:00:00Z",
    updatedAt: now,
  },
  {
    id: "clm-4",
    reference: "CLM-1032",
    moveId: "mv-complete-2day",
    customerName: "Helen & Robert Marsh",
    moveReference: "MV-COMPLETE-2D",
    status: "pending",
    category: "lost_item",
    title: "Missing lamp shade box",
    description: "One labeled box not found at delivery; search warehouse.",
    reportedDate: "2026-05-05",
    pendingReason: "customer",
    amountClaimed: 180,
    amountReserved: 120,
    amountPaid: 0,
    assignedTo: "Mia Chen",
    reportedBy: "Customer email",
    createdAt: "2026-05-05T11:00:00Z",
    updatedAt: now,
  },
  {
    id: "clm-5",
    reference: "CLM-1028",
    moveId: "mv-complete",
    customerName: "Denise Carter",
    moveReference: "MV-COMPLETE",
    status: "completed",
    category: "service",
    title: "Late arrival — goodwill credit",
    description: "Crew arrived 45 min late; offered service credit.",
    reportedDate: "2026-05-02",
    amountClaimed: 150,
    amountReserved: 150,
    amountPaid: 150,
    assignedTo: "Jordan Lee",
    reportedBy: "Coordinator",
    notes: "Credit applied to final invoice.",
    createdAt: "2026-05-02T16:00:00Z",
    updatedAt: "2026-05-04T10:00:00Z",
    resolvedAt: "2026-05-04T10:00:00Z",
  },
  {
    id: "clm-6",
    reference: "CLM-1021",
    moveId: "mv-quote-sent",
    customerName: "Nina & Tom Walsh",
    moveReference: "MV-QUOTE",
    status: "denied",
    category: "damage",
    title: "Pre-existing carpet stain",
    description: "Walkthrough photos show stain before load.",
    reportedDate: "2026-04-28",
    amountClaimed: 500,
    amountReserved: 0,
    amountPaid: 0,
    assignedTo: "Alex Rivera",
    reportedBy: "Claims review",
    notes: "Denied — not caused by crew.",
    createdAt: "2026-04-28T12:00:00Z",
    updatedAt: "2026-05-01T09:00:00Z",
    resolvedAt: "2026-05-01T09:00:00Z",
  },
];

export function defaultClaimsStore(): ClaimsStore {
  return { claims: DEFAULT_CLAIMS.map((c) => ({ ...c })) };
}
