import type { EquipmentCatalogItem } from "./equipment-catalog-types";

export const DEFAULT_EQUIPMENT_SUPPLY_CATALOG: EquipmentCatalogItem[] = [
  {
    id: "small_box",
    label: "Small box",
    unit: "ea",
    unitPrice: 4,
    category: "supply",
    showOnQuote: true,
    showOnContract: true,
  },
  {
    id: "medium_box",
    label: "Medium box",
    unit: "ea",
    unitPrice: 5,
    category: "supply",
    showOnQuote: true,
    showOnContract: true,
  },
  {
    id: "large_box",
    label: "Large box",
    unit: "ea",
    unitPrice: 7,
    category: "supply",
    showOnQuote: true,
    showOnContract: true,
  },
  {
    id: "packing_paper",
    label: "Packing paper (bundle)",
    unit: "bundle",
    unitPrice: 22,
    category: "supply",
    showOnQuote: true,
    showOnContract: true,
  },
  {
    id: "wardrobe_box",
    label: "Wardrobe box",
    unit: "ea",
    unitPrice: 18,
    category: "supply",
    showOnQuote: true,
    showOnContract: true,
  },
  {
    id: "tv_box",
    label: "TV box kit",
    unit: "ea",
    unitPrice: 35,
    category: "supply",
    showOnQuote: true,
    showOnContract: true,
  },
  {
    id: "dish_pack",
    label: "Dish pack kit",
    unit: "ea",
    unitPrice: 12,
    category: "supply",
    showOnQuote: true,
    showOnContract: false,
  },
  {
    id: "shrink_wrap",
    label: "Shrink wrap (roll)",
    unit: "roll",
    unitPrice: 28,
    category: "supply",
    showOnQuote: true,
    showOnContract: true,
  },
  {
    id: "mattress_bag",
    label: "Mattress bag",
    unit: "ea",
    unitPrice: 15,
    category: "supply",
    showOnQuote: true,
    showOnContract: false,
  },
  {
    id: "storage_blanket",
    label: "Storage blanket",
    unit: "ea",
    unitPrice: 0,
    category: "equipment",
    showOnQuote: false,
    showOnContract: false,
  },
  {
    id: "floor_runner",
    label: "Floor runner",
    unit: "ea",
    unitPrice: 0,
    category: "equipment",
    showOnQuote: false,
    showOnContract: false,
  },
  {
    id: "safe_dolly",
    label: "Safe dolly",
    unit: "ea",
    unitPrice: 0,
    category: "equipment",
    showOnQuote: false,
    showOnContract: false,
  },
];
