import { enrichMockMove } from "./mock-extras";
import { attachFollowUps } from "./mock-follow-ups";
import type { MoveCore } from "./move-core";
import type { MoveRecord } from "./types";

export type { MoveCore } from "./move-core";

const RAW_MOVES: MoveCore[] = [
  {
    id: "mv-new-lead",
    reference: "MV-NEW",
    pipelineStage: "new_lead",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "google",
    quoteChannel: "web_ai",
    intakeProgress: "started",
    websiteIntake: {
      sessionId: "web-sess-okonkwo",
      lastStepCompleted: "inventory",
      quotedAt: null,
      bookedAt: null,
    },
    contactId: "person-mv-new-lead-customer",
    customerName: "James Okonkwo move",
    customerPhone: "(216) 555-0411",
    customerEmail: "j.okonkwo@example.com",
    status: "new_request",
    source: "Website",
    assignedRep: "Jordan Lee",
    coordinator: null,
    moveType: "Local",
    originAddress: "12700 Lake Ave, Lakewood, OH",
    destinationAddress: "3400 W 117th St, Cleveland, OH",
    preferredDate: "2026-06-07",
    quoteAmount: null,
    quoteType: null,
    bedrooms: 2,
    createdAt: "2026-05-19T07:42:00Z",
    updatedAt: "2026-05-19T07:42:00Z",
    activities: [
      {
        id: "nl1",
        type: "note",
        at: "2026-05-19T07:42:00Z",
        summary: "Web intake — AI flat rate pending",
        actor: "System",
      },
    ],
  },
  {
    id: "mv-waiting-info",
    reference: "MV-INFO",
    pipelineStage: "waiting",
    waitingSubstage: "needs_info",
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "referral_business",
    contactId: "person-northside-office",
    customerName: "Northside Dental Group move",
    customerPhone: "(216) 555-0330",
    customerEmail: "office@northsidedental.example",
    status: "waiting",
    source: "Referral",
    assignedRep: "Alex Rivera",
    coordinator: null,
    moveType: "Commercial",
    originAddress: "6000 Rockside Rd, Independence, OH",
    destinationAddress: "8840 Mentor Ave, Mentor, OH",
    preferredDate: "2026-06-21",
    quoteAmount: null,
    quoteType: "flat",
    bedrooms: null,
    createdAt: "2026-05-17T08:15:00Z",
    updatedAt: "2026-05-18T13:00:00Z",
    activities: [
      {
        id: "ni1",
        type: "call",
        at: "2026-05-18T13:00:00Z",
        summary: "Waiting on equipment list & floor plans before quote",
        actor: "Alex Rivera",
      },
    ],
  },
  {
    id: "mv-waiting-walkthrough",
    reference: "MV-WALK",
    pipelineStage: "waiting",
    waitingSubstage: "walkthrough_scheduled",
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "referral_realtor",
    contactId: "person-peterson-executor",
    customerName: "Peterson Estate (executor) move",
    customerPhone: "(440) 555-0198",
    customerEmail: "jpeterson.law@example.com",
    status: "waiting",
    source: "Referral",
    assignedRep: "Jordan Lee",
    coordinator: null,
    moveType: "Local",
    originAddress: "88 Euclid Ave, Cleveland, OH",
    destinationAddress: "2100 Center Rd, Brunswick, OH",
    preferredDate: "2026-05-28",
    quoteAmount: 4800,
    quoteType: "flat",
    bedrooms: 4,
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-05-19T10:00:00Z",
    scheduledWalkthrough: {
      id: "wt-mv-waiting-walkthrough",
      scheduledDate: "2026-06-12",
      startTime: "10:00 AM",
      assignedTo: "Jordan Lee",
      mode: "in_person",
      status: "scheduled",
      location: "88 Euclid Ave, Cleveland, OH",
      bookedAt: "2026-05-19T10:00:00Z",
    },
    activities: [
      {
        id: "w1",
        type: "note",
        at: "2026-05-19T10:00:00Z",
        summary: "On-site walkthrough Jun 12 at 10:00 AM — estate contents",
        actor: "Jordan Lee",
      },
    ],
  },
  {
    id: "mv-needs-walkthrough",
    reference: "MV-NWT",
    pipelineStage: "waiting",
    waitingSubstage: "needs_walkthrough",
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "referral_realtor",
    contactId: "person-harbor-hoa",
    customerName: "Harbor View Condos (HOA) move",
    customerPhone: "(440) 555-0288",
    customerEmail: "board@harborviewcondos.example",
    status: "waiting",
    source: "Referral",
    assignedRep: "Alex Rivera",
    coordinator: null,
    moveType: "Commercial",
    originAddress: "1200 Harbor Blvd, Mentor, OH",
    destinationAddress: "1200 Harbor Blvd, Mentor, OH",
    preferredDate: "2026-06-18",
    quoteAmount: null,
    quoteType: "flat",
    bedrooms: null,
    createdAt: "2026-05-20T11:00:00Z",
    updatedAt: "2026-05-20T11:00:00Z",
    activities: [
      {
        id: "nwt1",
        type: "call",
        at: "2026-05-20T11:00:00Z",
        summary: "Clubhouse move — needs on-site walkthrough before flat quote",
        actor: "Alex Rivera",
      },
    ],
  },
  {
    id: "mv-quote-sent",
    reference: "MV-SENT",
    pipelineStage: "quote_sent",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "repeat_customer",
    contactId: "person-mv-quote-sent-customer",
    customerName: "Sarah & Tom Walsh move",
    customerPhone: "(216) 555-0142",
    customerEmail: "swalsh@example.com",
    status: "quote_sent",
    source: "Repeat customer",
    assignedRep: "Mia Chen",
    coordinator: null,
    moveType: "Local",
    originAddress: "1842 W 25th St, Cleveland, OH",
    destinationAddress: "9200 Detroit Ave, Lakewood, OH",
    preferredDate: "2026-06-14",
    quoteAmount: 1890,
    quoteType: "flat",
    bedrooms: 3,
    createdAt: "2026-05-12T14:20:00Z",
    updatedAt: "2026-05-18T16:45:00Z",
    activities: [
      {
        id: "qs1",
        type: "document",
        at: "2026-05-18T16:45:00Z",
        summary: "Proposal sent — pack Jun 13, move Jun 14",
        actor: "Mia Chen",
      },
    ],
  },
  {
    id: "mv-web-quoted",
    reference: "MV-WEBQ",
    pipelineStage: "quote_sent",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "google",
    quoteChannel: "web_ai",
    intakeProgress: "quoted",
    websiteIntake: {
      sessionId: "web-sess-hayes",
      lastStepCompleted: "quote",
      quotedAt: "2026-05-19T14:30:00Z",
      bookedAt: null,
    },
    contactId: "person-mv-web-quoted-customer",
    customerName: "Hayes Family move",
    customerPhone: "(216) 555-0622",
    customerEmail: "hayes.family@example.com",
    status: "quote_sent",
    source: "Website",
    assignedRep: "Alex Rivera",
    coordinator: null,
    moveType: "Local",
    originAddress: "9584 Doliver Dr, Houston, TX 77063",
    destinationAddress: "11210 Memorial Dr, Houston, TX 77024",
    preferredDate: "2026-06-18",
    quoteAmount: 2240,
    quoteType: "flat",
    bedrooms: 3,
    createdAt: "2026-05-19T14:30:00Z",
    updatedAt: "2026-05-19T14:30:00Z",
    activities: [
      {
        id: "wq1",
        type: "document",
        at: "2026-05-19T14:30:00Z",
        summary: "AI flat-rate quote generated on website — not booked yet",
        actor: "System",
      },
    ],
  },
  {
    id: "mv-needs-contract",
    reference: "MV-CONTRACT",
    pipelineStage: "needs_contract",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "referral_senior_living",
    contactId: "person-mv-needs-contract-customer",
    customerName: "Marcus & Dana Ellis move",
    customerPhone: "(216) 555-0719",
    customerEmail: "ellis.home@example.com",
    status: "needs_contract",
    source: "Referral",
    assignedRep: "Jordan Lee",
    coordinator: "Alex Rivera",
    moveType: "Long distance",
    originAddress: "4521 Euclid Ave, Cleveland, OH",
    destinationAddress: "1200 South Blvd, Charlotte, NC",
    preferredDate: "2026-06-01",
    quoteAmount: 195,
    quoteType: "hourly",
    bedrooms: 3,
    createdAt: "2026-04-28T09:00:00Z",
    updatedAt: "2026-05-19T11:00:00Z",
    activities: [
      {
        id: "nc1",
        type: "call",
        at: "2026-05-19T11:00:00Z",
        summary: "Verbal yes — hourly proposal $195/hr · contract pending",
        actor: "Jordan Lee",
      },
    ],
  },
  {
    id: "mv-booked",
    reference: "MV-BOOKED",
    pipelineStage: "booked",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "referral_realtor",
    contactId: "person-mv-booked-customer",
    customerName: "Chen Family move",
    customerPhone: "(216) 555-0281",
    customerEmail: "chen.family@example.com",
    status: "in_progress",
    source: "Referral",
    assignedRep: "Mia Chen",
    coordinator: "Alex Rivera",
    moveType: "Local",
    originAddress: "4501 Chester Ave, Cleveland, OH",
    destinationAddress: "11200 Shaker Blvd, Cleveland, OH",
    preferredDate: "2026-05-20",
    quoteAmount: 2450,
    quoteType: "flat",
    bedrooms: 4,
    createdAt: "2026-05-01T11:30:00Z",
    updatedAt: "2026-05-20T07:15:00Z",
    activities: [
      {
        id: "bk1",
        type: "status_change",
        at: "2026-05-20T07:15:00Z",
        summary: "Active job day — install in progress",
        actor: "Mia Chen",
      },
    ],
  },
  {
    id: "mv-ai-booked",
    reference: "MV-AI",
    pipelineStage: "booked",
    waitingSubstage: null,
    conditionStatus: "needs_review",
    bookingReviewStatus: "pending_review",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "website",
    quoteChannel: "web_ai",
    intakeProgress: "booked",
    websiteIntake: {
      sessionId: "web-sess-ortiz",
      lastStepCompleted: "book",
      quotedAt: "2026-05-20T05:55:00Z",
      bookedAt: "2026-05-20T06:00:00Z",
    },
    contactId: "person-mv-ai-booked-customer",
    customerName: "Riley & Sam Ortiz move",
    customerPhone: "(216) 555-0555",
    customerEmail: "ortiz.home@example.com",
    status: "booked",
    source: "Website",
    assignedRep: "Jordan Lee",
    coordinator: null,
    moveType: "Local",
    originAddress: "2200 Superior Ave, Cleveland, OH",
    destinationAddress: "9900 Detroit Ave, Lakewood, OH",
    preferredDate: "2026-06-02",
    quoteAmount: 1780,
    quoteType: "flat",
    bedrooms: 2,
    createdAt: "2026-05-20T06:00:00Z",
    updatedAt: "2026-05-20T06:00:00Z",
    activities: [
      {
        id: "ai1",
        type: "status_change",
        at: "2026-05-20T06:00:00Z",
        summary: "AI website booking — pending team review",
        actor: "System",
      },
    ],
  },
  {
    id: "mv-complete",
    reference: "MV-DONE",
    pipelineStage: "completed",
    waitingSubstage: null,
    conditionStatus: "closed",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "repeat_customer",
    contactId: "person-mv-complete-customer",
    customerName: "Angela Brooks move",
    customerPhone: "(216) 555-0823",
    customerEmail: "abrooks@example.com",
    status: "completed",
    source: "Phone",
    assignedRep: "Mia Chen",
    coordinator: "Alex Rivera",
    moveType: "Local",
    originAddress: "1500 E 12th St, Cleveland, OH",
    destinationAddress: "7800 Detroit Ave, Lakewood, OH",
    preferredDate: "2026-05-18",
    quoteAmount: 1650,
    quoteType: "flat",
    bedrooms: 2,
    createdAt: "2026-04-20T11:00:00Z",
    updatedAt: "2026-05-18T17:00:00Z",
    activities: [
      {
        id: "co1",
        type: "status_change",
        at: "2026-05-18T17:00:00Z",
        summary: "Move complete — final payment collected",
        actor: "Mia Chen",
      },
    ],
  },
  {
    id: "mv-complete-2day",
    reference: "MV-2DAY",
    pipelineStage: "completed",
    waitingSubstage: null,
    conditionStatus: "closed",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "referral_realtor",
    contactId: "person-mv-complete-2day-customer",
    customerName: "Robert & Diana Chen move",
    customerPhone: "(216) 555-0318",
    customerEmail: "chen.family@example.com",
    status: "completed",
    source: "Referral",
    assignedRep: "Mia Chen",
    coordinator: "Alex Rivera",
    moveType: "Local",
    originAddress: "1840 Coventry Rd, Cleveland Heights, OH",
    destinationAddress: "9200 Detroit Ave, Lakewood, OH",
    preferredDate: "2026-05-10",
    quoteAmount: 4850,
    quoteType: "flat",
    bedrooms: 4,
    createdAt: "2026-04-28T10:00:00Z",
    updatedAt: "2026-05-11T18:30:00Z",
    activities: [
      {
        id: "co2d1",
        type: "status_change",
        at: "2026-05-10T19:15:00Z",
        summary: "Day 1 complete — pack & load to truck",
        actor: "Alex Rivera",
      },
      {
        id: "co2d2",
        type: "status_change",
        at: "2026-05-11T18:30:00Z",
        summary: "Day 2 complete — delivered & final payment collected",
        actor: "Mia Chen",
      },
    ],
  },
  {
    id: "mv-lost",
    reference: "MV-LOST",
    pipelineStage: "quote_sent",
    waitingSubstage: null,
    conditionStatus: "lost",
    bookingReviewStatus: "not_required",
    lostAt: "2026-05-08T14:00:00Z",
    lostFromStage: "quote_sent",
    lostReason: "Qualified · Chose competitor",
    lostQualification: "qualified",
    lostReasonId: "competitor",
    lostNotes: null,
    leadChannel: "facebook",
    contactId: "person-mv-lost-customer",
    customerName: "Former Lead — Lee Household move",
    customerPhone: "(216) 555-0999",
    customerEmail: "lee@example.com",
    status: "lost",
    source: "Website",
    assignedRep: "Jordan Lee",
    coordinator: null,
    moveType: "Local",
    originAddress: "4100 Pearl Rd, Cleveland, OH",
    destinationAddress: "55 E Mill St, Akron, OH",
    preferredDate: "2026-06-15",
    quoteAmount: 2100,
    quoteType: "flat",
    bedrooms: 2,
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-05-08T14:00:00Z",
    activities: [
      {
        id: "lo1",
        type: "status_change",
        at: "2026-05-08T14:00:00Z",
        summary: "Marked lost from Quote Sent — chose competitor",
        actor: "Jordan Lee",
      },
    ],
  },
  {
    id: "mv-ds-long",
    reference: "MV-DS-L",
    pipelineStage: "booked",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "referral_realtor",
    contactId: "person-mv-ds-long-customer",
    customerName: "Chen move",
    customerPhone: "(216) 555-0601",
    customerEmail: "chen.long@example.com",
    status: "booked",
    source: "Referral",
    assignedRep: "Mia Chen",
    coordinator: null,
    moveType: "Long distance",
    originAddress: "1200 W 6th St, Cleveland, OH",
    destinationAddress: "8900 Euclid Ave, Cleveland, OH",
    preferredDate: "__TOMORROW__",
    quoteAmount: 4200,
    quoteType: "flat",
    bedrooms: 4,
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-05T14:00:00Z",
    activities: [],
  },
  {
    id: "mv-ds-medium",
    reference: "MV-DS-M",
    pipelineStage: "booked",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "google",
    contactId: "person-mv-ds-medium-customer",
    customerName: "Walsh move",
    customerPhone: "(216) 555-0602",
    customerEmail: "walsh@example.com",
    status: "booked",
    source: "Phone",
    assignedRep: "Alex Rivera",
    coordinator: null,
    moveType: "Local",
    originAddress: "3200 Detroit Ave, Cleveland, OH",
    destinationAddress: "14500 Triskett Rd, Cleveland, OH",
    preferredDate: "__TOMORROW__",
    quoteAmount: 1850,
    quoteType: "flat",
    bedrooms: 3,
    createdAt: "2026-06-02T11:00:00Z",
    updatedAt: "2026-06-05T14:00:00Z",
    activities: [],
  },
  {
    id: "mv-ds-short-am",
    reference: "MV-DS-SA",
    pipelineStage: "booked",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "google_maps",
    contactId: "person-mv-ds-short-am-customer",
    customerName: "Ellis move",
    customerPhone: "(216) 555-0604",
    customerEmail: "ellis@example.com",
    status: "booked",
    source: "Website",
    assignedRep: "Mia Chen",
    coordinator: null,
    moveType: "Local",
    originAddress: "5500 Turney Rd, Garfield Heights, OH",
    destinationAddress: "7700 Broadway Ave, Cleveland, OH",
    preferredDate: "__TOMORROW__",
    quoteAmount: 890,
    quoteType: "flat",
    bedrooms: 2,
    createdAt: "2026-06-03T09:00:00Z",
    updatedAt: "2026-06-05T14:00:00Z",
    activities: [],
  },
  {
    id: "mv-ds-short-pm",
    reference: "MV-DS-SP",
    pipelineStage: "booked",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "repeat_customer",
    contactId: "person-mv-ds-short-pm-customer",
    customerName: "Morales move",
    customerPhone: "(216) 555-0605",
    customerEmail: "morales@example.com",
    status: "booked",
    source: "Repeat customer",
    assignedRep: "Alex Rivera",
    coordinator: null,
    moveType: "Local",
    originAddress: "11200 Shaker Blvd, Cleveland, OH",
    destinationAddress: "4501 Chester Ave, Cleveland, OH",
    preferredDate: "__TOMORROW__",
    quoteAmount: 850,
    quoteType: "flat",
    bedrooms: 2,
    createdAt: "2026-06-03T10:00:00Z",
    updatedAt: "2026-06-05T14:00:00Z",
    activities: [],
  },
  {
    id: "mv-ds-brief-pm",
    reference: "MV-DS-BP",
    pipelineStage: "booked",
    waitingSubstage: null,
    conditionStatus: "active",
    bookingReviewStatus: "not_required",
    lostAt: null,
    lostFromStage: null,
    lostReason: null,
    leadChannel: "website",
    contactId: "person-mv-ds-brief-pm-customer",
    customerName: "Parker move",
    customerPhone: "(216) 555-0603",
    customerEmail: "parker@example.com",
    status: "booked",
    source: "Website",
    assignedRep: "Jordan Lee",
    coordinator: null,
    moveType: "Local",
    originAddress: "9800 Lorain Ave, Cleveland, OH",
    destinationAddress: "2200 W 25th St, Cleveland, OH",
    preferredDate: "__TOMORROW__",
    quoteAmount: 590,
    quoteType: "flat",
    bedrooms: 1,
    createdAt: "2026-06-02T12:00:00Z",
    updatedAt: "2026-06-05T14:00:00Z",
    activities: [],
  },
];

function withFollowUps(core: MoveCore): MoveRecord {
  const enriched = enrichMockMove(core);
  switch (core.id) {
    case "mv-waiting-info":
      return attachFollowUps(enriched, [
        {
          type: "info_request",
          title: "Request missing inventory info",
          dueAt: "2026-05-18T17:00:00Z",
          channel: "email",
          linkedStage: "waiting",
        },
      ]);
    case "mv-quote-sent":
      return attachFollowUps(enriched, [
        {
          type: "proposal_follow_up",
          title: "Follow up on proposal",
          dueAt: "2026-05-22T10:00:00Z",
          channel: "call",
          linkedStage: "quote_sent",
          source: "automation",
        },
        {
          type: "custom",
          title: "Call back — customer asked for Saturday pricing",
          dueAt: "2026-05-19T15:00:00Z",
          channel: "call",
          linkedStage: "quote_sent",
          source: "manual",
        },
        {
          type: "custom",
          title: "Send packing tips email",
          dueAt: "2026-06-15T10:00:00Z",
          channel: "email",
          linkedStage: "quote_sent",
          source: "scheduled",
        },
      ]);
    case "mv-needs-contract":
      return attachFollowUps(enriched, [
        {
          type: "contract_reminder",
          title: "Send contract reminder",
          dueAt: "2026-05-20T14:00:00Z",
          channel: "email",
          linkedStage: "needs_contract",
        },
      ]);
    case "mv-booked":
      return attachFollowUps(enriched, [
        {
          type: "ops_coordination",
          title: "Confirm elevator reservation",
          dueAt: "2026-05-21T09:00:00Z",
          channel: "call",
          linkedStage: "booked",
        },
      ]);
    case "mv-new-lead":
      return attachFollowUps(enriched, [
        {
          type: "first_contact",
          title: "Web intake abandoned — finish quote or call back",
          dueAt: "2026-05-19T17:00:00Z",
          channel: "call",
          linkedStage: "new_lead",
        },
      ]);
    case "mv-web-quoted":
      return attachFollowUps(enriched, [
        {
          type: "proposal_follow_up",
          title: "Web AI quote — follow up to book",
          dueAt: "2026-05-21T10:00:00Z",
          channel: "call",
          linkedStage: "quote_sent",
        },
      ]);
    case "mv-ai-booked":
      return attachFollowUps(enriched, [
        {
          type: "booking_confirm",
          title: "Review AI booking — kickoff call & verify quote",
          dueAt: "2026-05-20T12:00:00Z",
          channel: "call",
          linkedStage: "booked",
        },
      ]);
    case "mv-complete":
    case "mv-complete-2day":
      return attachFollowUps(enriched, [
        {
          type: "review_request",
          title: "Ask for review",
          dueAt: "2026-05-25T10:00:00Z",
          channel: "email",
          linkedStage: "completed",
          status: "completed",
        },
      ]);
    default:
      return attachFollowUps(enriched, []);
  }
}

export const MOCK_MOVES: MoveRecord[] = RAW_MOVES.map(withFollowUps);

export const PIPELINE_DEMO_MOVE_IDS = [
  "mv-new-lead",
  "mv-web-quoted",
  "mv-waiting-info",
  "mv-waiting-walkthrough",
  "mv-needs-walkthrough",
  "mv-quote-sent",
  "mv-needs-contract",
  "mv-booked",
  "mv-ai-booked",
  "mv-complete",
  "mv-complete-2day",
] as const;

export function getMoveById(id: string): MoveRecord | undefined {
  return MOCK_MOVES.find((m) => m.id === id);
}

/** @deprecated */
export const LIFECYCLE_DEMO_MOVE_IDS = PIPELINE_DEMO_MOVE_IDS;
